apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nginx
  description: A description of your account management repository.
  tags:
    - production
    - kubernetes
    - backend
  links:
    - url: https://backstage.io/docs/features/software-catalog/well-known-annotations/#backstageioview-url-backstageioedit-url
      title: Onboarding documentation
      icon: dashboard
      type: admin-dashboard
    - url: https://backstage.io/docs/features/software-catalog/system-model
      title: Techincal documentation
      icon: dashboard
      type: admin-dashboard
  annotations:
    backstage.io/kubernetes-id: nginx
    kafka.apache.org/consumer-groups: localhost/my-consumer-group,localhost/my-consumer-group2
    github.com/project-slug: 'backstage/backstage'
spec:
  type: service
  lifecycle: production
  owner: guest
