apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accountmanagement
  description: A description of your account management repository.
spec:
  type: service
  lifecycle: production
  owner: junaidaj86
